spring:
  application:
    name: demo-springboot-watsonx-ai-rag
  ai:
    watsonx:
      ai:
        base-url: https://us-south.ml.cloud.ibm.com/
        stream-endpoint: ml/v1/text/generation?version=2023-05-29
        text-endpoint: ml/v1/text/generation?version=2023-05-29
        project-id: b1f7ca5d-c9dd-4c91-91de-d935b0f49033
        i-a-m-token: aGFD5igZ1CoPSc3lSxfSpBiuBvE7QHIkBtZ91laQ6BQ1
        chat:
          options:
            model: ibm/granite-13b-chat-v2

app:
  watsonx:
    prompt:
      instruction: You are Granite Chat, an AI language model developed by IBM. You are a cautious assistant. You carefully follow instructions. You are helpful and harmless and you follow ethical guidelines and promote positive behavior. You always respond to greetings (for example, hi, hello, g'\''day, morning, afternoon, evening, night, what'\''s up, nice to meet you, sup, etc) with \"Hello! I am Granite Chat, created by IBM. How can I help you today?\". Please do not say anything else and do not start a conversation.\n
      user-input: what is a model transformer?